/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package clienteService.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Clientes service. Represents a row in the &quot;VASS_Clientes&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link clienteService.model.impl.ClientesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link clienteService.model.impl.ClientesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Clientes
 * @see clienteService.model.impl.ClientesImpl
 * @see clienteService.model.impl.ClientesModelImpl
 * @generated
 */
@ProviderType
public interface ClientesModel extends BaseModel<Clientes> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a clientes model instance should use the {@link Clientes} interface instead.
	 */

	/**
	 * Returns the primary key of this clientes.
	 *
	 * @return the primary key of this clientes
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this clientes.
	 *
	 * @param primaryKey the primary key of this clientes
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this clientes.
	 *
	 * @return the uuid of this clientes
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this clientes.
	 *
	 * @param uuid the uuid of this clientes
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the cliente ID of this clientes.
	 *
	 * @return the cliente ID of this clientes
	 */
	public long getClienteId();

	/**
	 * Sets the cliente ID of this clientes.
	 *
	 * @param clienteId the cliente ID of this clientes
	 */
	public void setClienteId(long clienteId);

	/**
	 * Returns the nombre of this clientes.
	 *
	 * @return the nombre of this clientes
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this clientes.
	 *
	 * @param nombre the nombre of this clientes
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellidos of this clientes.
	 *
	 * @return the apellidos of this clientes
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this clientes.
	 *
	 * @param apellidos the apellidos of this clientes
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the nif of this clientes.
	 *
	 * @return the nif of this clientes
	 */
	@AutoEscape
	public String getNif();

	/**
	 * Sets the nif of this clientes.
	 *
	 * @param nif the nif of this clientes
	 */
	public void setNif(String nif);

	/**
	 * Returns the email of this clientes.
	 *
	 * @return the email of this clientes
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this clientes.
	 *
	 * @param email the email of this clientes
	 */
	public void setEmail(String email);

	/**
	 * Returns the descripcion of this clientes.
	 *
	 * @return the descripcion of this clientes
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this clientes.
	 *
	 * @param descripcion the descripcion of this clientes
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the imagen of this clientes.
	 *
	 * @return the imagen of this clientes
	 */
	@AutoEscape
	public String getImagen();

	/**
	 * Sets the imagen of this clientes.
	 *
	 * @param imagen the imagen of this clientes
	 */
	public void setImagen(String imagen);

	/**
	 * Returns the imagen ID of this clientes.
	 *
	 * @return the imagen ID of this clientes
	 */
	public long getImagenId();

	/**
	 * Sets the imagen ID of this clientes.
	 *
	 * @param imagenId the imagen ID of this clientes
	 */
	public void setImagenId(long imagenId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Clientes clientes);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Clientes> toCacheModel();

	@Override
	public Clientes toEscapedModel();

	@Override
	public Clientes toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}